# Generated by Django 4.0.3 on 2023-07-26 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_appointment_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='vip',
        ),
    ]
