# Generated by Django 4.0.3 on 2023-07-26 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_remove_appointment_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment', to='service_rest.technician'),
        ),
    ]
